### ISSUE TITLE
Add events modality

### ISSUE THREAD

**Issue by gyroflaw** [casper-ecosystem/cep18#56] opened 2023-02-23 07:23 UTC
# Background

Currently, no events are emitted when user triggers actions - `transfer`, `burn`, etc.

# Suggestion
This should be fixed by using [CES](https://github.com/make-software/casper-event-standard).
If this issue is accepted, the [js-client](https://github.com/casper-ecosystem/erc20/tree/feature/js-client/client) should be updated.

we will do this by adding an events modality, in the pattern of our cep78 implementation:

1. no events (default)d
2. CES events

**Comment by RitaMAllenCA** [comment] 2023-05-22 21:19
duplicate of #73

**Closed by RitaMAllenCA** 2023-05-22 21:19 UTC
